### ISSUE TITLE
Tests don't work?

### ISSUE THREAD

**Issue by kud** [gajus/create-index#58]
```
> create-index@1.1.0 test /Users/kud/Projects/_kud/create-index
> npm run build && npm run lint && cross-env NODE_ENV=development mocha --compilers js:babel-register


> create-index@1.1.0 build /Users/kud/Projects/_kud/create-index
> cross-env NODE_ENV=production babel --source-maps --copy-files ./src --out-dir ./dist

src/bin/create-index.js -> dist/bin/create-index.js
src/index.js -> dist/index.js
src/utilities/constants.js -> dist/utilities/constants.js
src/utilities/createIndexCode.js -> dist/utilities/createIndexCode.js
src/utilities/findIndexFiles.js -> dist/utilities/findIndexFiles.js
src/utilities/hasIndex.js -> dist/utilities/hasIndex.js
src/utilities/index.js -> dist/utilities/index.js
src/utilities/log.js -> dist/utilities/log.js
src/utilities/readDirectory.js -> dist/utilities/readDirectory.js
src/utilities/readIndexConfig.js -> dist/utilities/readIndexConfig.js
src/utilities/sortByDepth.js -> dist/utilities/sortByDepth.js
src/utilities/validateTargetDirectory.js -> dist/utilities/validateTargetDirectory.js
src/utilities/writeIndex.js -> dist/utilities/writeIndex.js
src/utilities/writeIndexCli.js -> dist/utilities/writeIndexCli.js

> create-index@1.1.0 lint /Users/kud/Projects/_kud/create-index
> cross-env NODE_ENV=development eslint ./src ./tests

canonical:
	Configuration for rule "import/first" is invalid:
	Value "[object Object]" is the wrong type.

Referenced from: /Users/kud/Projects/_kud/create-index/.eslintrc
Error: canonical:
	Configuration for rule "import/first" is invalid:
	Value "[object Object]" is the wrong type.

Referenced from: /Users/kud/Projects/_kud/create-index/.eslintrc
    at validateRuleOptions (/Users/kud/Projects/_kud/create-index/node_modules/eslint/lib/config/config-validator.js:109:15)
    at /Users/kud/Projects/_kud/create-index/node_modules/eslint/lib/config/config-validator.js:156:13
    at Array.forEach (<anonymous>)
    at Object.validate (/Users/kud/Projects/_kud/create-index/node_modules/eslint/lib/config/config-validator.js:155:35)
    at load (/Users/kud/Projects/_kud/create-index/node_modules/eslint/lib/config/config-file.js:559:19)
    at /Users/kud/Projects/_kud/create-index/node_modules/eslint/lib/config/config-file.js:424:36
    at Array.reduceRight (<anonymous>)
    at applyExtends (/Users/kud/Projects/_kud/create-index/node_modules/eslint/lib/config/config-file.js:408:28)
    at Object.load (/Users/kud/Projects/_kud/create-index/node_modules/eslint/lib/config/config-file.js:566:22)
    at loadConfig (/Users/kud/Projects/_kud/create-index/node_modules/eslint/lib/config.js:63:33)
(node:32294) Warning: Accessing non-existent property 'cat' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
(node:32294) Warning: Accessing non-existent property 'cd' of module exports inside circular dependency
(node:32294) Warning: Accessing non-existent property 'chmod' of module exports inside circular dependency
(node:32294) Warning: Accessing non-existent property 'cp' of module exports inside circular dependency
(node:32294) Warning: Accessing non-existent property 'dirs' of module exports inside circular dependency
(node:32294) Warning: Accessing non-existent property 'pushd' of module exports inside circular dependency
(node:32294) Warning: Accessing non-existent property 'popd' of module exports inside circular dependency
(node:32294) Warning: Accessing non-existent property 'echo' of module exports inside circular dependency
(node:32294) Warning: Accessing non-existent property 'tempdir' of module exports inside circular dependency
(node:32294) Warning: Accessing non-existent property 'pwd' of module exports inside circular dependency
(node:32294) Warning: Accessing non-existent property 'exec' of module exports inside circular dependency
(node:32294) Warning: Accessing non-existent property 'ls' of module exports inside circular dependency
(node:32294) Warning: Accessing non-existent property 'find' of module exports inside circular dependency
(node:32294) Warning: Accessing non-existent property 'grep' of module exports inside circular dependency
(node:32294) Warning: Accessing non-existent property 'head' of module exports inside circular dependency
(node:32294) Warning: Accessing non-existent property 'ln' of module exports inside circular dependency
(node:32294) Warning: Accessing non-existent property 'mkdir' of module exports inside circular dependency
(node:32294) Warning: Accessing non-existent property 'rm' of module exports inside circular dependency
(node:32294) Warning: Accessing non-existent property 'mv' of module exports inside circular dependency
(node:32294) Warning: Accessing non-existent property 'sed' of module exports inside circular dependency
(node:32294) Warning: Accessing non-existent property 'set' of module exports inside circular dependency
(node:32294) Warning: Accessing non-existent property 'sort' of module exports inside circular dependency
(node:32294) Warning: Accessing non-existent property 'tail' of module exports inside circular dependency
(node:32294) Warning: Accessing non-existent property 'test' of module exports inside circular dependency
(node:32294) Warning: Accessing non-existent property 'to' of module exports inside circular dependency
(node:32294) Warning: Accessing non-existent property 'toEnd' of module exports inside circular dependency
(node:32294) Warning: Accessing non-existent property 'touch' of module exports inside circular dependency
(node:32294) Warning: Accessing non-existent property 'uniq' of module exports inside circular dependency
(node:32294) Warning: Accessing non-existent property 'which' of module exports inside circular dependency
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! create-index@1.1.0 lint: `cross-env NODE_ENV=development eslint ./src ./tests`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the create-index@1.1.0 lint script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/kud/.npm/_logs/2020-05-12T11_34_15_533Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! create-index@1.1.0 test: `npm run build && npm run lint && cross-env NODE_ENV=development mocha --compilers js:babel-register`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the create-index@1.1.0 test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/kud/.npm/_logs/2020-05-12T11_34_15_577Z-debug.log
```

**Comment by gajus** [comment]
Fixed.

**Comment by kud** [comment]
Thank you!
